### ISSUE TITLE
Project cannot be built

### ISSUE THREAD

**Issue by 0x0blu** [yahiafarghaly/Embedded_Calculator-AVR#1]
There are several errors that prevent building this project, and are as follows:
- The first line in "methods.c" is not commented out.
- Datatypes are not declared in "method.c". (Maybe you should #include "std_types" at top of "method.c" file.)
- "strrev" function in "method.c" is not declared.
- #include "Components/...". No such directory called "Components".
- Files "micro_config.h", "common_macros.h" and "initialization.h" are not there, even outside "Components" directory.

**Comment by blucell** [comment]
Found that others also are missing, like LCD & Keypad libraries.

**Comment by 0x0blu** [comment]
Found that others, like LCD and Keypad libraries are not there, too.

**Comment by yahiafarghaly** [comment]
@blucell all files are added, you can clone now and do whatever you want
